# Generated by Django 4.0.4 on 2022-05-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('username', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=150)),
            ],
        ),
    ]
