# Generated by Django 4.0.4 on 2022-05-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
