# Generated by Django 4.0.4 on 2022-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_date_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='okonchanie',
            field=models.TimeField(null=True, verbose_name='%H:%M'),
        ),
    ]
