# Generated by Django 4.0.4 on 2022-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_date_okonchanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='stol_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
