# Generated by Django 4.0.4 on 2022-05-07 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_date_stol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='stol_id',
        ),
    ]
