# Generated by Django 4.0.4 on 2022-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_date_nachalo_alter_date_okonchanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='nachalo',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='okonchanie',
            field=models.TimeField(null=True),
        ),
    ]
