# Generated by Django 4.0.4 on 2022-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_date_price_alter_date_nachalo_alter_date_okonchanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='stol_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
