# Generated by Django 4.0.4 on 2022-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_date_stol_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='id',
        ),
        migrations.AlterField(
            model_name='date',
            name='stol_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
