# Generated by Django 4.0.4 on 2022-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_date_id_date_stol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='stol_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='tg_id'),
        ),
    ]
