# Generated by Django 4.0.4 on 2022-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_date_stol_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='stol_id',
            field=models.IntegerField(auto_created=True, unique=True),
        ),
    ]
