# Generated by Django 4.0.4 on 2022-05-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField()),
                ('name', models.TextField()),
                ('quantity', models.IntegerField()),
                ('price', models.TextField()),
            ],
        ),
    ]
