# Generated by Django 4.0.4 on 2022-05-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='active',
        ),
    ]
