# Generated by Django 4.0.4 on 2022-05-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_bar_bar_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='nachalo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='okonchanie',
            field=models.DateTimeField(null=True),
        ),
    ]
