# Generated by Django 4.0.4 on 2022-05-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_date_nachalo_alter_date_okonchanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='name',
            field=models.TextField(),
        ),
    ]
