# Generated by Django 4.0.4 on 2022-05-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_date_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
