# Generated by Django 4.0.4 on 2022-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_date_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
