# Generated by Django 4.0.4 on 2022-05-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_date_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
