# Generated by Django 4.0.4 on 2022-05-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_date_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='active',
        ),
    ]
